// AUTO-GENERATED — alan-5 — FRACTURE EVENTS
function AlanCh5({ tweaks, basePage = 1 }) {
  const tier = tweaks.intrusionTier;
  const dataAttrs = { "data-body": tweaks.chenBody || "garamond" };
  const ChPage = (props) => <Page book="chen" dataAttrs={dataAttrs} showTexture {...props} />;
  const AlPage = (props) => <Page book="alan" showTexture {...props} />;
  const IlPage = (props) => <Page book="interlude" showTexture={false} {...props} />;
  return (<>
    <Spread id="alan-5-opener" label="FRACTURE EVENTS · opener">
      <AlPage side="verso" label="(blank)" />
      <AlPage side="recto" label="alan-5 · opener">
        <AlanChapterHead entry={5} sub="FRACTURE EVENTS" coord="[TEMPORAL LOG // ENTRY_005 // ERA: 62 // NODE: FRACTURE]" />
        <AlanFragment top={170} right={4} rotate={-3} size={9}>// 2287.240.0001</AlanFragment>
      </AlPage>
    </Spread>
    <Spread id="alan-5-02" label="FRACTURE EVENTS · spread 2">
      <AlPage side="verso" runHead="ENTRY_005" pageNum={basePage + 2} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 2}`}>
        <aside className="al-fragment"><p>{inline(`Chen thinks of these guys as panic attacks because she still believes you can survive them through technique.`)}</p><p>{inline(`I call them what they are. A Crisis is something that happens to you. A Fracture is something you become.`)}</p><p>{inline(`Fractures have three sounds. First: a high whine you mistake for the building. Then: the silence after the whine, which is the silence of a system finishing a calculation. Then: the calculation's output, which is the new shape of you.`)}</p><p>{inline(`Three Fractures live in this chapter. Each has its own physics. All three sound the same in the first thirty seconds.`)}</p><div className="al-fragment__sign">// AR</div></aside>
        <aside className="al-fragment"><p>{inline(`The first Fracture Event isn't the worst one.`)}</p><p>{inline(`The worst one is the one that made the category exist. The one that made someone sit down and say, we need a word for this. We need a formal mechanical framework for the thing that happens when four people are in a room together and at the end of it there are only three categories of person left in the world.`)}</p><p>{inline(`You don't need the details. You'll Fracture in your own way.`)}</p><div className="al-fragment__sign">// AR</div></aside>
        <AlanBody><p>{inline(`Fractures occur when your current configuration becomes untenable. Three triggers: `)}<b>{inline(`Coherence -6`)}</b>{inline(` (Desynchronization), `)}<b>{inline(`Paradox 10+`)}</b>{inline(` (Breach), `)}<b>{inline(`Corruption Vector 0`)}</b>{inline(` (Final Transformation).`)}</p></AlanBody>
        <h4 className="al-subsection">{inline(`Three-Phase Resolution`)}</h4>
        <AlanBody><p>{inline(`PHASE 1: MANIFESTATION`)}</p></AlanBody>
        <AlanBody><p>{inline(`Roll on the appropriate Oracle. Pay the immediate cost: lose 1 Coherence, one Scar becomes Fading, mark 1 Asset Stress.`)}</p></AlanBody>
        <AlanBody><p>{inline(`PHASE 2: ESCALATION`)}</p></AlanBody>
        <AlanBody><p>{inline(`If Paradox `)}<b>{inline(`10+`)}</b>{inline(` (Breach), Faction Intervention occurs during Phase 2. Roll `)}<b>{inline(`d4`)}</b>{inline(`: 1 = Church, 2 = Authority, 3 = Scionfall, 4 = Chronoclasts. Or pick whichever makes narrative sense.`)}</p></AlanBody>
      </AlPage>
      <AlPage side="recto" runHead="ENTRY_005" pageNum={basePage + 3} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 3}`}>
        <AlanBody><p>{inline(`CHURCH INTERVENTION (emiT) Templars arrive. They want your Scars — the weaponized trauma you've been accumulating is holy to them. Roll `)}<b>{inline(`2d6`)}</b>{inline(` + DISRUPT or ENDURE (`)}<b>{inline(`Difficulty 10`)}</b>{inline(`).`)}</p></AlanBody>
        <div className="al-resolution"><div className="resolution-row"><div className="resolution-roll">{`10+`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Fight them off`)}</div><div className="resolution-text">{inline(`Gain +2 Paradox from the violence. Gain +1 Corruption Vector decrease from the exposure to their harvesting field.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`7-9`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Escape damaged`)}</div><div className="resolution-text">{inline(`They strip one of your Active Scars as a tithe. Lose its bonus permanently. They leave satisfied.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`6-`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Taken`)}</div><div className="resolution-text">{inline(`Quick Resolution: lose 2 Coherence, one Scar is harvested (bonus gone, becomes Lost, gain Mutation), Paradox reduced by 3. You're released. Or play Appendix E: Harmonic Crucifixion.`)}</div></div></div></div>
        <AlanBody><p>{inline(`AUTHORITY INTERVENTION (emiT) Clone Loop. They're trying to normalize you back into the baseline — but you've Mutated past easy correction. The loop can't quite contain you anymore. Roll `)}<b>{inline(`2d6`)}</b>{inline(` + OBSERVE (`)}<b>{inline(`Difficulty 10`)}</b>{inline(`).`)}</p></AlanBody>
      </AlPage>
    </Spread>
    <Spread id="alan-5-03" label="FRACTURE EVENTS · spread 3">
      <AlPage side="verso" runHead="ENTRY_005" pageNum={basePage + 4} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 4}`}>
        <div className="al-resolution"><div className="resolution-row"><div className="resolution-roll">{`10+`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Slip the pattern`)}</div><div className="resolution-text">{inline(`You recognize the recursion before it sets. No cost. The Authority marks you as a Loop-Resistant anomaly —they'll escalate next time.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`7-9`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Partially looped`)}</div><div className="resolution-text">{inline(`Two iterations. Each one costs 1 Active Scar (becomes Fading). Then the loop dissolves —your Mutations create too much instability to hold.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`6-`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Full loop`)}</div><div className="resolution-text">{inline(`Quick Resolution: all Active Scars become Fading, Paradox reduced by `)}<b>{inline(`1d6`)}</b>{inline(`. They release you —processing you was more destabilizing than containing you. Or play Appendix E: Loop Containment Protocol.`)}</div></div></div></div>
        <AlanBody><p>{inline(`SCIONFALL INTERVENTION (emiT) A Herald manifests. The Nullwave field expands. For a Wreck at your stage, the offer isn't cessation — it's integration. Absorption into the Scionfall archive as a preserved configuration. Roll `)}<b>{inline(`2d6`)}</b>{inline(` + ENDURE (`)}<b>{inline(`Difficulty 10`)}</b>{inline(`).`)}</p></AlanBody>
        <div className="al-resolution"><div className="resolution-row"><div className="resolution-roll">{`10+`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Resist`)}</div><div className="resolution-text">{inline(`The warmth recedes. Paradox reduced by 1 (the Nullwave bled some off). They note your resistance. They'll send a Herald with better numbers next time.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`7-9`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Partial absorption`)}</div><div className="resolution-text">{inline(`One Scar is integrated —archived by Scionfall, no longer yours. You feel its absence as a specific kind of silence. Paradox reduced by 2.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`6-`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Offer accepted or forced`)}</div><div className="resolution-text">{inline(`Quick Resolution: Corruption Vector decreases by 1, Paradox cleared entirely, gain a Scionfall-aligned Mutation. You're still you. Just also theirs. Or play Appendix E: Nullwave Protocol.`)}</div></div></div></div>
      </AlPage>
      <AlPage side="recto" runHead="ENTRY_005" pageNum={basePage + 5} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 5}`}>
        <AlanBody><p>{inline(`CHRONOCLAST INTERVENTION (emiT) They don't intervene. They appear and watch. A Wreck at high Paradox is interesting to them — the contamination patterns, the Mutation cascade, the aesthetic of a person becoming something unprecedented. Roll `)}<b>{inline(`2d6`)}</b>{inline(` + SYNC (`)}<b>{inline(`Difficulty 8`)}</b>{inline(`).`)}</p></AlanBody>
        <div className="al-resolution"><div className="resolution-row"><div className="resolution-roll">{`10+`}</div><div className="resolution-body"><div className="resolution-title">{inline(`They're impressed`)}</div><div className="resolution-text">{inline(`They offer a gift: choose one —reduce Paradox by 3, clear all Asset Stress, or gain a new Mutation of your choice. They leave humming.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`7-9`}</div><div className="resolution-body"><div className="resolution-title">{inline(`They collaborate`)}</div><div className="resolution-text">{inline(`They make one change to your current situation —something chaotic, something that makes things worse and more interesting simultaneously. You didn't ask for this. Gain +1 Paradox, gain +1 to your next roll.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`6-`}</div><div className="resolution-body"><div className="resolution-title">{inline(`You're the art now`)}</div><div className="resolution-text">{inline(`They add you to something. What, you don't know. Your next Paradox generation roll produces double the normal amount. This lasts until Repreival.`)}</div></div></div></div>
        <AlanBody><p>{inline(`PHASE 3: RESOLUTION`)}</p></AlanBody>
        <AlanBody><p>{inline(`Standard Resolution: Roll `)}<b>{inline(`2d6`)}</b>{inline(` + ENDURE (`)}<b>{inline(`Difficulty 10`)}</b>{inline(`).`)}</p></AlanBody>
      </AlPage>
    </Spread>
    <Spread id="alan-5-04" label="FRACTURE EVENTS · spread 4">
      <AlPage side="verso" runHead="ENTRY_005" pageNum={basePage + 6} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 6}`}>
        <div className="al-resolution"><div className="resolution-row"><div className="resolution-roll">{`12+`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Stabilize completely`)}</div><div className="resolution-text">{inline(`Restore some resources.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`10-11`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Stabilize with consequences`)}</div><div className="resolution-text">{inline(`Fracture ends.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`7-9`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Barely survive`)}</div><div className="resolution-text">{inline(`Major loss —Scar, Asset, or Corruption Vector decrease.`)}</div></div></div><div className="resolution-row"><div className="resolution-roll">{`6-`}</div><div className="resolution-body"><div className="resolution-title">{inline(`Configuration fails`)}</div><div className="resolution-text">{inline(`Choose: Transform or Dissolve.`)}</div></div></div></div>
        <h4 className="al-subsection">{inline(`ALTERNATIVE: EMBRACE CORRUPTION`)}</h4>
        <AlanBody><p>{inline(`Roll `)}<b>{inline(`2d6 + DISRUPT`)}</b>{inline(` (Difficulty `)}<b>{inline(`8`)}</b>{inline(`) instead. Lower difficulty, but automatic consequences: `)}<b>{inline(`Corruption Vector decreases by 1`)}</b>{inline(`, gain a `)}<b>{inline(`Mutation`)}</b>{inline(`, mark `)}<b>{inline(`+3 Paradox`)}</b>{inline(`, gain a new operational `)}<b>{inline(`Capability`)}</b>{inline(`.`)}</p></AlanBody>
        <aside className="al-fragment"><p>{inline(`Crisis as transformation opportunity. Easier door. Higher exit cost.`)}</p><div className="al-fragment__sign">// AR</div></aside>
      </AlPage>
      <AlPage side="recto" runHead="ENTRY_005" pageNum={basePage + 7} coordStamp="[LOG // ENTRY_005]" label={`FRACTURE EVENTS · p.${basePage + 7}`}>
        
      </AlPage>
    </Spread>
  </>);
}

AlanCh5.pages = 8;
Object.assign(window, { AlanCh5 });
