// AUTO-GENERATED — chapter/chen ch4 — CORE RESOLUTION & FACTION PRESSURE
function ChenCh4({ tweaks, basePage = 1 }) {
  const tier = tweaks.intrusionTier;
  const dataAttrs = { "data-body": tweaks.chenBody || "garamond" };
  const ChPage = (props) => <Page book="chen" dataAttrs={dataAttrs} showTexture {...props} />;
  const AlPage = (props) => <Page book="alan" showTexture {...props} />;
  const IlPage = (props) => <Page book="interlude" showTexture={false} {...props} />;
  return (<>
    <Spread id="chen-4-01" label="CORE RESOLUTION & FACTION PRESSURE · spread 1">
      <ChPage side="verso" label="(blank)" />
      <ChPage side="recto" showWatermark label="Chen Ch 4 · Opener">
        <ChenChapterHead icon="assets/chen-icon-broken-compass.svg" number="IV" title="Core Resolution & Faction Pressure" />
      </ChPage>
    </Spread>
    <Spread id="chen-4-02" label="CORE RESOLUTION & FACTION PRESSURE · spread 2">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 2)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 2)}`}>
        <h3 style={{margin:'4mm 0 1mm', fontFamily:"var(--ff-serif-display)", fontWeight:600, fontSize:'12pt', color:'var(--el-forest)', fontVariant:'small-caps', letterSpacing:'0.08em'}}>The Resolution</h3>
        <ChenBody columns={1}><p>{inline(`Roll`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`When the outcome matters, you roll. Two six-sided dice, plus the relevant Mode, plus your Memory bonus if one applies. 10+ is success. 7-9 is success with cost. 6- is failure with an opening. I want to say something about the 6- before we go further. New Echoes treat it as the bad result. It isn't. The 10+ ends the question; the 6- changes it. Both move the story. Only one of them surprises you.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><p>{inline(`When you attempt something risky or opposed, make a Resolution Roll:`)}</p></ChenBody>
        <h2 className="el-h2">RESOLUTION</h2>
        <ChenBody columns={1}><p>{inline(`Roll: 2d6 + Mode Rating + Memory Bonus`)}</p></ChenBody>
        <h2 className="el-h2">MEMORY BONUS</h2>
        <ChenBody columns={1}><p>{inline(`Active Memory matching context +2 Fading Memory matching context +1 Locked Memory matching context +3 No relevant Memory +0 **10+** Complete Success —achieve goal, +1 Wave Coherence **7-9** Success with Complication —succeed, cost or new problem **6-** Failure with Opportunity —fail, but gain something useful Choose: Lose 1 Coherence OR Mark 1 Paradox`)}</p></ChenBody>
        
      </ChPage>
      <ChPage side="recto" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 3)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 3)}`}>
        <ChenBody columns={1}><p>{inline(`Navigation You will be displaced whether you want to be or not. Faction interference, Crisis events, and temporal instability will throw you between eras involuntarily. But you can also attempt Precision Navigation — using resonance principles to target specific coordinates in time.`)}</p></ChenBody>
        <h2 className="el-h2">PRECISION NAVIGATION</h2>
        <ChenBody columns={1}><p>{inline(`When you attempt to reach a specific era or location: Step 1: Define Your Target. Specify as precisely as you can — when (year, decade, or century), where (city, region, or continent), and why (what you're seeking there, which helps focus the resonance). Your precision affects the Difficulty:`)}</p></ChenBody>
        <h2 className="el-h2">TARGET PRECISION DIFFICULTY</h2>
        <ChenBody columns={1}><p>{inline(`Specific date & location (June 23, 1848, 12 Rue Saint-Jacques, Paris) Year & city (1848, Paris) 10 Decade & region (1840s, France) 8 Century & continent (1800s, Europe) 7 Step 2: Pay the Cost. Spend 1 Coherence before rolling. When you have 0 Coherence, you cannot attempt Precision Navigation. Step 3: Roll 2d6 + OBSERVE + Memory Bonus (if applicable). Step 4: Read the result:`)}</p></ChenBody>
        <h2 className="el-h2">STRUCTURED CORRECTION</h2>
        <ChenBody columns={1}><p>{inline(`**12+** Perfect Resonance. Arrive exactly when and where intended. Gain +1 Coherence (clean synchronization). No Paradox generated. **10-11** Successful Navigation. Arrive at intended era and location. Minor variance (different street, day off by a week). Mark +1 Paradox from resonance strain. **7-9** Close Arrival. Arrive in correct era OR correct location, not both. Same year, different city, OR same city, years off. Mark +1 Paradox. **6-** Lost in Transit. Navigation fails. Consult the Anomaly Tables (see below). Choose: Lose 1 Coherence OR Mark +2 Paradox.`)}</p></ChenBody>
        
      </ChPage>
    </Spread>
    <Spread id="chen-4-03" label="CORE RESOLUTION & FACTION PRESSURE · spread 3">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 4)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 4)}`}>
        <ChenBody columns={1}><p>{inline(`After rolling all four Anomaly Tables, you may spend 1 Coherence to reroll one result. Choose which table to reroll (ERA, LOCATION, ANOMALY, or COMPLICATION), spend the Coherence, and accept the new result. You may do this once per displacement event.`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`Initial observations can contain measurement error. Temporal resonance creates interference. If you invest the Coherence to recalibrate, you can refine your assessment. This isn't changing reality. It's correcting your perception of what exists.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><p>{inline(`NAVIGATION COLLAPSE (PARADOX 7+) At Paradox 7 or higher, your waveform is too unstable for resonance-targeting. You have lost fine control. AT PARADOX 7+: NAVIGATION COLLAPSE You cannot roll Precision Navigation. State your intention ('I'm trying to reach 1848 Paris'). All displacement is determined by the Anomaly Tables. Structured Correction still applies. To restore Precision Navigation, reduce Paradox below 7.`)}</p></ChenBody>
        <div style={{margin:'4mm -2mm', background:'rgba(13,15,18,0.94)', color:'var(--al-ghost)', fontFamily:'var(--ff-hand)', fontSize:'13pt', lineHeight:1.25, padding:'4mm 6mm', transform:'rotate(-0.6deg)', boxShadow:'0 2px 8px rgba(13,15,18,0.35)'}}><p style={{margin:0}}>Chen frames it as agency vs. passivity. She's way offbase. The only choice is between paying for the illusion of control and admitting you don't have any. Anomaly Tables are cheaper because they're not selling you anything.</p><div style={{textAlign:'right', marginTop:'2mm', fontSize:'11pt', opacity:0.85}}>—AR</div></div>
        <ChenBody columns={1}><p>{inline(`Wave Coherence`)}</p></ChenBody>
        <AlanIntrusion top={83} side="left" outset={-8} rotate={-1.50} width={58} tier={tier}>Chen's into spending Coherence to make the dice lie more comfortably. Sure, it works. It's also false comfort.</AlanIntrusion>
      </ChPage>
      <ChPage side="recto" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 5)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 5)}`}>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`Coherence is the integrity of your harmonic signature. It holds you to a single line of self when everything around you is trying to dissolve you into static. It is the most expensive resource you have and one you will spend without noticing you spent it. Track Coherence on a scale from +6 to -6. Each value corresponds to a state you can feel — if you have the discipline to feel it before you've already passed it.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><p>{inline(`Wave Coherence measures how aligned you are with the timestream. It ranges from -6 to your Anchor Strength + 5 (usually 8).`)}</p></ChenBody>
        <h2 className="el-h2">COHERENCE STATE EFFECT</h2>
        <ChenBody columns={1}><p>{inline(`Synchronized (+6 to +8) +1 to all Resolution rolls. You move through time with grace. Flux (0 to +5) No modifier. Normal operation. Desynchronizing (-1 to -5) -1 to all Resolution rolls. Time is hostile. Crisis (-6) -2 to all Resolution rolls. Immediate Desynchronization Crisis.`)}</p></ChenBody>
        <h2 className="el-h2">GAINING AND LOSING COHERENCE</h2>
        <ChenBody columns={1}><p>{inline(`You gain Coherence when you succeed (+1 on a 10+), when you write something true in your Chronicle (+1), when you reinforce your Anchor (+2). You lose it when you fail (-1 on a 6-, or choose Paradox instead), when you're Displaced (see Displacement Costs below), when you let a Memory fade (-1), when your Anchor takes Stress (see Anchor Stress below). The math is simple. The choices aren't.`)}</p></ChenBody>
        <h2 className="el-h2">DISPLACEMENT COSTS</h2>
        <ChenBody columns={1}><p>{inline(`Every time you are Displaced — voluntarily or not — you lose Coherence from the wrenching dislocation. Displacement Type Coherence Cost Precision Navigation (voluntary) -1 (paid before rolling) Failed Navigation (6-) -1 or +2 Paradox (your choice) Forced Displacement — Faction interference, -2 Crisis, random jump Crisis Displacement — Shattering, Identity -3`)}</p></ChenBody>
        
      </ChPage>
    </Spread>
    <Spread id="chen-4-04" label="CORE RESOLUTION & FACTION PRESSURE · spread 4">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 6)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 6)}`}>
        <ChenBody columns={1}><p>{inline(`collapse, Breach Involuntary jumps always cost 2. Crisis-level displacement costs 3. You don't get to choose when those happen. That's the point.`)}</p></ChenBody>
        <h2 className="el-h2">ANCHOR STRESS</h2>
        <ChenBody columns={1}><p>{inline(`Your Anchor is not invulnerable. Certain events put direct pressure on your connection to your origin — not enough to break it, but enough to require maintenance. Your Anchor has a Stress track: ○○○ Mark 1 Anchor Stress when: A Church Templar successfully captures or touches you (their rituals target your origin frequency directly) You fail a roll involving your Locked Memory while in Desynchronization Crisis (-1 to -5 Coherence) You spend Downtime in an era that directly contradicts a core Anchor Connection (you knew her as alive; here she died before you were born) A Crisis outcome specifies Anchor Stress When all 3 Anchor Stress boxes are marked, your Anchor is Strained. While Strained: you cannot invoke Anchor Connections for Coherence bonuses. The Reinforce Anchor move (Ch. 7) clears Stress as normal — but on a 6-, you lose 1 Anchor Strength permanently instead of just failing. Clear Anchor Stress during Downtime Step 2.`)}</p></ChenBody>
        <h2 className="el-h2">COHERENCE OVERFLOW</h2>
        <ChenBody columns={1}><p>{inline(`When you would gain Coherence but are already at your maximum, choose one: Stabilize an Asset (clear 1 Stress from any Asset), Reduce Contamination (reduce Paradox by 1, if above 0), or Bank It (mark +1 Banked Coherence, maximum 3 Banked). Spend Banked Coherence 1-for-1 to prevent Coherence loss. This mechanic exists in Temporal Echoes only. Wrecks do not bank Coherence. You're not preserving anything. Paradox: The Universe Pushing Back`)}</p></ChenBody>
        
      </ChPage>
      <ChPage side="recto" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 7)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 7)}`}>
        <ChenBody columns={1}><p>{inline(`Paradox accumulates through interference. The universe keeps count even when you don't. Action Paradox Contradict your own Chronicle +1 Share knowledge from the wrong era (a technique, a fact, a warning) +1 Change something small — redirect one person, save one life, +1 alter one decision Change something documented — an event with witnesses, +2 a death with records Create a causal loop (you caused the thing that caused you here) +2 Meet yourself (any version — past, future, alternate) +2 Change something load-bearing — a battle's outcome, +3 a discovery's timing, a leader's survival Cause a Shattering deliberately +3 When in doubt: if people would write it down afterward, it's +2. If people would change how they understand history, it's +3. If only you noticed, it's +1.`)}</p></ChenBody>
        <h2 className="el-h2">PARADOX BAND EFFECTS</h2>
        <ChenBody columns={1}><p>{inline(`Shadow (0-3) — No penalties. Small reality glitches: déjà vu, objects slightly wrong. Invisible to Factions. Flux (4-6) — -1 to Resolution rolls. Noticeable anomalies. Memory Fading accelerates. Faction Scouts appear when you roll 6-. Anomaly (7-9) — -1 to Resolution rolls. Memory Fading doubles. Reality actively hostile. Faction Agents appear as complication on 7-9. Breach (10+) — -2 to Resolution rolls. Timeline collapsing. Immediate Paradox Crisis. Faction Intervention during Crisis Phase 2.`)}</p></ChenBody>
        
      </ChPage>
    </Spread>
    <Spread id="chen-4-05" label="CORE RESOLUTION & FACTION PRESSURE · spread 5">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 8)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 8)}`}>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`The modifiers above are designed to compound. So are the modifiers from Coherence states, Faction Marks, and unfavored Modes. At low Paradox and stable Coherence, the math is forgiving. At high Paradox and Crisis Coherence, it is hostile. This is deliberate. I will say more about it in Chapter 6. What you should know now: when the stack turns against you, better dice will not save you. The systems the game has been holding in reserve will. Engage them.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><p>{inline(`Faction Pressure`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`You are a foreign object in a closed system. The Chronoverse has an immune response, and your Paradox is the fever it is responding to. The Factions are antibodies with philosophies. Containment, harvest, euthanasia — none of these are moral failures on their part, and accepting an Offer is not a moral failure on yours. They are not after you because they hate you. They are after you because you are fuel.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <h2 className="el-h2">SHADOW (0-3): INVISIBLE</h2>
        <ChenBody columns={1}><p>{inline(`You're background noise. Factions have no reason to notice something they can't measure. Enjoy it. It won't last.`)}</p></ChenBody>
        <h2 className="el-h2">FLUX (4-6): SCOUTS APPEAR</h2>
        <ChenBody columns={1}><p>{inline(`When you roll 6-, a Scout appears. Roll d4: 1 = Church Observer, 2 = Authority Surveyor, 3 = Scionfall Herald, 4 = Chronoclast. Automatic if you're already Marked. Scouts watch. They file reports. They don't act — they're waiting to see if you're worth the effort.`)}</p></ChenBody>
        <h2 className="el-h2">ANOMALY (7-9): AGENTS APPEAR</h2>
        <ChenBody columns={1}><p>{inline(`When you roll 7-9, a Faction Agent appears as your complication. They've decided you're worth the effort. They make an Offer. Roll d4 for which Faction, or automatic if Marked. This is when the game changes. BREACH (10+): INTERVENTION During Crisis Phase 2, Factions arrive in force. You're not a nuisance anymore. You're a crisis event. Roll d4, or d4 twice for a Factional War — two Factions competing over what to do with you. See Crisis Interventions in Chapter 6.`)}</p></ChenBody>
        
      </ChPage>
      <ChPage side="recto" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 9)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 9)}`}>
        <h3 style={{margin:'4mm 0 1mm', fontFamily:"var(--ff-serif-display)", fontWeight:600, fontSize:'12pt', color:'var(--el-forest)', fontVariant:'small-caps', letterSpacing:'0.08em'}}>Agent Encounters</h3>
        <ChenBody columns={1}><p>{inline(`When an Agent appears at Paradox 7-9, they bring an Offer. The form varies — surveillance, interference, demand, or direct confrontation. Not every Agent encounter is a fight. You choose one of three responses: Accept the Offer. Pay the cost, gain the benefit. Offers are trades, not rolls. Refuse. They impose a consequence and Mark you. Drive Off. Make a roll to force them away. Offers are your non-roll path to Paradox relief. If Downtime moves aren't working, an Agent's trade is how you buy back control — by selling pieces of yourself.`)}</p></ChenBody>
        <h2 className="el-h2">THE DRIVE OFF MOVE</h2>
        <ChenBody columns={1}><p>{inline(`Roll 2d6 + DISRUPT (Difficulty 10): 10+ Success. You drive them off through violence or intimidation. No additional cost. They retreat. You're not Marked. 7-9 Success with cost. They retreat. Choose one: lose 2 Coherence, mark +1 Paradox, or they Mark you anyway. 6- Failure. You fail. Take their Imposed consequence AND they Mark you. They leave when they're done with you. The Four Agents`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`The four below are not exhaustive. They are the four I have met often enough to describe consistently. Each Faction has variations — older Templars, younger Auditors, Heralds wearing a face you have not yet lost, Chronoclasts who have learned restraint. The descriptions are what holds across the variations. The faces change. The function does not.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`CHURCH TEMPLAR`)}</li></ol></ChenBody>
        <ChenBody columns={1}><p>{inline(`They appear bleeding through their era-appropriate armor, chrono-glyphs inscribed into the metal. The thing you notice first are their eyes — millennia of pain mixed with purpose and pleasure. The Offer: Your pain can have purpose. Let us use it.`)}</p></ChenBody>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`The Trade: Take 1 Scar immediately + lose 2 Coherence →Reduce Paradox by 3. Mark: Church knows you're a viable battery. They'll return. If Refused: Impose — their prayer weighs on you, lose 1 Coherence. Mark — next Scout/Agent encounter is automatically Church.`)}</li><li>{inline(`AUTHORITY AUDITOR`)}</li></ol></ChenBody>
        <ChenBody columns={1}><p>{inline(`Forgettable in the way that only deliberate design achieves. A grey suit that wears a human being. Takes notes. Blinks and their clothes change slightly. The Offer: You're glitching. We can smooth you out. Become efficient again. The Trade: Choose one Active Memory — it becomes normalized (bonus drops from +2 to +0, emotional context erased). →Reduce Paradox by 2, clear 1 Stress from one Asset. Mark: They've tagged your waveform. If Refused: Impose — -1 to Navigation rolls until next Downtime. Mark — they begin preparing a Clone Loop.`)}</p></ChenBody>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`SCIONFALL HERALD`)}</li></ol></ChenBody>
        <ChenBody columns={1}><p>{inline(`They always appear as a loved one. Kind eyes, warm voice, something underneath that is steel all the way through. The Offer: I can end the pain. All of it. Right now. The Trade: Character retired. You cease. Peacefully. Game over. Write a final Chronicle entry: I let go. This is a valid ending — choosing peace over continued suffering. If Refused: Impose — -1 to ENDURE while they're present. Mark — the offer stands, always. They'll return during your next Crisis.`)}</p></ChenBody>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`CHRONOCLAST REMIXER`)}</li></ol></ChenBody>
        <ChenBody columns={1}><p>{inline(`Anachronism incarnate. Carrying objects from the wrong era. Laughing at things that aren't funny. The Offer: You're making art! Here — let's make it louder. The Trade: Gain +2 Paradox now →Gain +3 to your next DISRUPT or OBSERVE roll only. Regardless of result, that roll triggers a Complication. Mark: they think you're interesting. If Refused: Impose — roll on Timeline Shift Oracle immediately (reality changes around you). Mark — they'll bring a gift next time (unstable Chrono-Tech that glitches constantly).`)}</p></ChenBody>
        
      </ChPage>
    </Spread>
    <Spread id="chen-4-06" label="CORE RESOLUTION & FACTION PRESSURE · spread 6">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 10)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 10)}`}>
        <h2 className="el-h2">BEING MARKED</h2>
        <h3 style={{margin:'4mm 0 1mm', fontFamily:"var(--ff-serif-display)", fontWeight:600, fontSize:'12pt', color:'var(--el-forest)', fontVariant:'small-caps', letterSpacing:'0.08em'}}>When a Faction</h3>
        <ChenBody columns={1}><p>{inline(`Marks you, write in your Chronicle: MARKED: [Faction name]. The next time that Faction would appear, they appear automatically — no d4 roll needed. Once they appear, erase the Mark. You can be Marked by multiple Factions simultaneously.`)}</p></ChenBody>
        <div style={{margin:'4mm -2mm', background:'rgba(13,15,18,0.94)', color:'var(--al-ghost)', fontFamily:'var(--ff-hand)', fontSize:'13pt', lineHeight:1.25, padding:'4mm 6mm', transform:'rotate(-0.6deg)', boxShadow:'0 2px 8px rgba(13,15,18,0.35)'}}><p style={{margin:0}}>Being Marked means you're screwed. You drew their attention, refused their offer, and now they know you're worth effort. I've been Marked by all four Factions simultaneously. It's like having four different kinds of cancer. Each one convinced they're helping.</p><div style={{textAlign:'right', marginTop:'2mm', fontSize:'11pt', opacity:0.85}}>—AR</div></div>
        <ChenBody columns={1}><p>{inline(`Downtime`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`Downtime is the part of the work nobody else does for you. When a session ends, or when the era is briefly not actively trying to kill you, stop and write down what happened. Repair what you can. Many good Echoes faded because they did not take Downtime with the rigor it deserves.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <h2 className="el-h2">WHEN TO TAKE DOWNTIME</h2>
        <ChenBody columns={1}><p>{inline(`After every Precision Navigation roll, OR After every Oracle Displacement (rolling all four Anomaly Tables), OR At the end of your real-world play session, if neither of the above occurred.`)}</p></ChenBody>
        <h2 className="el-h2">DOWNTIME STEPS (DO THESE IN ORDER)</h2>
        <ChenBody columns={1}><p>{inline(`Chronicle the Session. 1.`)}</p></ChenBody>
        <ChenMarginalia top={69} side="left" outset={-18} rotate={-1.50} width={38}>Being Marked doesn't mean immediate danger — it means they're watching. They know your resonance signature now. You've become a bookmark in their archives.</ChenMarginalia>
      </ChPage>
      <ChPage side="recto" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 11)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 11)}`}>
        <ChenBody columns={1}><p>{inline(`Write in your Chronicle: where/when you are, what happened this session, one significant choice you made, one thing you lost or changed. This is mandatory. Chronicling is how you stabilize memory. Effect: gain +1 Coherence, up to your maximum. Reinforce Your Anchor. If your Anchor took Stress during the session, roll 2d6 + SYNC (Difficulty 10). On 10+: clear all Stress. On 7-9: clear 1 Stress, and either spend time and resources on it or leave remaining Stress. On 6-: no Stress cleared. Tend to Assets. For each Asset with Stress marked, roll 2d6 + relevant Mode (usually OBSERVE for tech, SYNC for connections). On 10+: clear all Stress. On 7-9: clear 1 Stress. On 6-: no Stress cleared. If an Asset has all Stress marked, it's broken — spend a Downtime move repairing it (narrate the work, no roll) or replace it with a new Asset at Level 1. Process Memory. Your memory system naturally degrades. The oldest Active Memory moves to Fading (loses +2 bonus, now +1). The oldest Fading Memory becomes Lost. When a Memory becomes Lost, gain a Scar (see Chapter 5). When a memory passes from Active to Fading, you notice it as effort — the thing you used to recall instantly now requires you to reach. Fading to Lost is quieter. You don't notice the moment it goes. You notice, weeks later, that something used to be there and now is not. You reach for the cup that isn't there. You start the sentence and find no end to it. The Scar is the shape the absence leaves. Your Locked Memory never fades. If something significant happened this session, you may create a new Memory: write the event, choose Context Tags, write a description. It enters Active Slot 1, pushing everything else forward. Reduce Paradox (Optional). Choose one: Temporal Grounding: Spend significant time integrating with the current era. Roll 2d6 + SYNC (Difficulty 10). On 10+: reduce Paradox by 2. On 7-9: reduce by 1. On 6-: no reduction, lose 1 Coherence from the exhaustion.`)}</p></ChenBody>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`Ritual Purification: Use specialized Chrono-Tech or Faction assistance. Effect: reduce Paradox by 1d6, but if using Church methods, take 1 Mutation; if using Authority methods, normalize 1 Scar (reduce bonus to +0); if using tech, the Asset takes all Stress. Ignore: Accept your current contamination level. Plan Next Move. Answer one of these questions in your Chronicle: What am I trying to accomplish? What am I afraid will happen next? What do I need that I don't have?`)}</li></ol></ChenBody>
        <h2 className="el-h2">SAFETY TOOLS</h2>
        <ChenBody columns={1}><p>{inline(`This game explores identity dissolution, memory loss, isolation, and the horror of losing yourself piece by piece. The Temporal Pause (X-Card): At any point, if the content becomes too intense, stop writing. Close the Chronicle. Breathe. Narratively, your Echo phases out of local time for a micro-second, avoiding the trauma. Mechanically, skip the scene. No penalty. Reality redraws itself around the gap. Lines and Veils: Lines are events that don't happen in your timeline — write them in the back of your Chronicle under Redacted Data. If an Oracle prompts them, reroll. Veils are events that happen off-screen — describe the setup and aftermath, but the event itself is Lost to Static.`)}</p></ChenBody>
        <h2 className="el-h2">EXPANDED SAFETY TOOLS</h2>
        <ChenBody columns={1}><p>{inline(`Temporal Echoes is a game about loss, memory, and identity erosion. Played at length, it will put you in proximity to real feelings you may not have scheduled time for. The following tools exist to help you engage with difficult material without getting genuinely hurt. Lines and Veils Before your first session, take ten minutes to write two short lists in the front of your Chronicle. Lines — content that will not appear in your game, ever. Hard stops. If the Oracle rolls toward it, you reroll or narrate around it. There is no mechanical cost for this. The game's rules have no authority over what you're willing to encounter. Veils — content that may exist in the world of the game but is not described on-page. Violence happens, but you don't zoom in on it. A character dies, but you cut to the next scene. Fade to black is a legitimate move.`)}</p></ChenBody>
        <ChenBody columns={1}><ol style={{margin:'2mm 0', paddingLeft:'5mm'}}><li>{inline(`Your Lines and Veils can change between sessions. Cross things out. Add new ones. You are not locked in. The Temporal Pause (X-Card Equivalent) At any point, if the content of the scene is genuinely affecting you in a way you didn't sign up for — not uncomfortable-in-a-good- way, not sad-about-fictional-things, but actually-bad-for-you — close the book. Stand up. Walk away. The game does not require completion. Your Echo does not lose Coherence because you put the book down. A session you stopped is a session. You can come back, or you can choose not to. Both are legal. Fast Forward If a scene is going somewhere you'd rather not dwell — an interrogation, a captivity vignette, a loss of a specific Anchor Connection — you may narrate through it in a single paragraph and move on. Record only the outcome. Pay any mechanical costs. Do not detail the content. This is not cheating. The mechanics work the same. You just don't linger. Rewind If you make a narrative choice and, an hour later, realize it sent the story somewhere you don't want to go, you may Rewind. Cross out the last paragraph of your Chronicle. Return to the prior decision point. Choose differently. Pay the mechanical costs of any rolls that occurred. Keep any Scars. The fiction is yours to revise. The accumulated damage is not. Processing Difficult Content Temporal Echoes deliberately engages with memory loss, grief, identity dissolution, and the specific horror of outliving your own ability to feel things. The game was built by someone processing their own experience of these, and many of the people who play it are doing the same. A few practices that help if you are one of them. Decouple the Echo from yourself. Name them something other than your own name. Give them an origin era you did not live in. The distance is what makes the catharsis possible without it bleeding into your actual life.`)}</li></ol></ChenBody>
        
      </ChPage>
    </Spread>
    <Spread id="chen-4-07" label="CORE RESOLUTION & FACTION PRESSURE · spread 7">
      <ChPage side="verso" runHead="Core Resolution & Faction Pressure" pageNum={(basePage + 12)} label={`Chen · CORE RESOLUTION & FACTION PRESSURE · p.${(basePage + 12)}`}>
        <ChenBody columns={1}><p>{inline(`Keep a separate notebook — not the Chronicle — for one line per session about how the session affected you. Not how it affected your Echo. This is not part of the game. It is part of being a person who plays the game. If a session leaves you raw, talk to a person who exists in your life before you pick the book up again. The Chronicle is a mirror, and a mirror is not the same thing as company. A Note on Crisis If you are in genuine mental-health crisis — the kind that does not belong in a game — please set the book aside and contact a crisis line in your region, or a trusted person. The game will still be here. You need to be too.`)}</p></ChenBody>
        <div style={{margin:'4mm 0', paddingLeft:'5mm', borderLeft:'0.5pt solid var(--el-gold)', fontStyle:'italic', fontFamily:'var(--ff-serif-body)', fontSize:'9.5pt', lineHeight:1.4, color:'var(--el-annotation)'}}><p style={{margin:0}}>{inline(`Gödel proved that any formal system rich enough to express arithmetic contains true statements it cannot prove. Reality, under CTH, is the same. There are facts about the timeline that are true and that the timeline cannot accommodate. Echoes bear those facts carved into their identity, but Paradox is what happens when an unprovable truth tries to find a place to stand.`)}</p><div style={{textAlign:'right', marginTop:'1mm', fontSize:'8.5pt', fontStyle:'italic'}}>— EC</div></div>
        <ChenBody columns={1}><p>{inline(`Memoria finita est.`)}</p></ChenBody>
        <AlanIntrusion top={122} side="left" outset={-8} rotate={-1.50} width={58} tier={tier}>Chen calls them an immune system. Cute framing. An immune system protects the body. The factions don't protect anything. They digest you and call the digestion mercy, order, freedom, art. Pick your enzyme.</AlanIntrusion>
      </ChPage>
      <ChPage side="recto" label="(blank)" />
    </Spread>
  </>);
}

ChenCh4.pages = 13;
Object.assign(window, { ChenCh4 });